name: Run Tests

run-name: Running Tests



on: [push]

jobs:
  trail-ubuntu-run:
    runs-on: ubuntu-latest
    steps:
    #clone the github to the runner system
      - uses: actions/checkout@v4

      - name: check file
        run: |
          cd Source 
          ls -a

      # Read the solution file and make sure it has the correct unreal engine version
      - name: Check Unreal Engine target version in solution file
        run: |
          FILE_PATH="TimeParadox.uproject"
          
          if grep -q '"EngineAssociation": "5.4"' "$FILE_PATH"; then
            echo "Project solution correctly configured to run on UE5"
          else
            echo "Error: Project solution not configured to run on UE5"
            exit 1
          fi

      # Read the Target.cs file and make sure it has the correct unreal engine version
      - name: Check Unreal Engine target version in Target.cs file
        run: |
          FILE_PATH="TimeParadox.Target.cs"
          cd Source 

          
          if grep -q "IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_4;" "$FILE_PATH"; then
            echo "Project correctly configured to run on UE5"
          else
            echo "Error: Project not configured to run on UE5"
            exit 1
          fi

        # Read the TimeParadox.Build.cs file andCheck that the correct dependencies are included
      - name: Check that the correct dependencies are included
        run: |
          FILE_PATH="TimeParadox.Build.cs"
          cd Source 
          cd TimeParadox


          
          if grep -q '"Core", "CoreUObject", "Engine", "InputCore", "EnhancedInput"' "$FILE_PATH"; then
            echo "Project project dependencies properly included"
          else
            echo "Error: Project project dependencies not included"
            exit 1
          fi
        # New test to build the Unity game
      - name: Build Unity Game
        uses: game-ci/unity-builder@v2
        with:
          projectPath: 'TimeParadox'  # Adjust path to your Unity project
          unityVersion: '2021.3.11f1'  # Adjust Unity version as needed
          targetPlatform: StandaloneOSX  # Adjust platform (e.g., StandaloneWindows, StandaloneLinux)
      
        # Check if the build output was generated
      - name: Verify Unity Build
        run: |
          if [ -d "TimeParadox/Builds" ]; then
            echo "Unity build completed successfully."
          else
            echo "Error: Unity build failed."
            exit 1
          fi  



       
