name: Run Tests

run-name: Running Tests



on: [push]

jobs:
  trail-ubuntu-run:
    runs-on: ubuntu-latest
    steps:
    #clone the github to the runner system
      - uses: actions/checkout@v4



      # Read the Target.cs file and make sure it has the correct unreal engine version
      - name: Check Unreal Engine target version in Target.cs file
        run: |
         FILE_PATH="Games/TimeParadox/Source/TimeParadox.Target.cs"

         if[-f "$FILE_PATH"]; then

          if grep -q "IncludeOrderVersion = EngineIncludeOrderVersion.Unreal5_4;" "$FILE_PATH"; then
            echo "Project correctly configured to run on UE5"
          else
            echo "Error: Project not configured to run on UE5"
            exit 1
          fi



       
